# 站点设置
title: UNIC 实验室本科生实习招生
description: >
  泛在网络与智能计算研究组（UNIC）诚邀优秀本科生加入我们的实习项目。
  在这里，你将接触前沿的学术研究，与一流的研究团队合作，
  聚焦生成式电磁空间与数字孪生、空天地一体化5G/6G通信网络、AI4Sci 与 Sci4AI 等方向。
baseurl: ""
url: "https://unic-lab.github.io"
permalink: /:title/
repository: UNIC-Lab/unic-lab.github.io

# MatJek 特定配置
github_profile: "https://github.com/UNIC-Lab"
user: "泛在网络与智能计算研究组（UNIC）"
user_email: ""
contact_url: "https://unicxidian.org/"

# 构建设置
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
